# Generated by Django 4.2.7 on 2023-11-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_complated', models.BooleanField(default=False, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('amout', models.CharField(max_length=255, verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'История',
                'verbose_name_plural': 'ИМтории',
            },
        ),
    ]
