# Generated by Django 4.2.7 on 2023-11-08 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historytransfer', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historytransfer',
            old_name='amout',
            new_name='amount',
        ),
    ]
